-- =============================================================================
-- MyCoaching — Initial database schema
-- Target: Supabase (PostgreSQL)
-- Generated from DATABASE.md + TypeScript models.
--
-- HOW TO USE:
--   1. Create a new Supabase project.
--   2. Open the SQL Editor.
--   3. Paste this whole file and Run.
--   4. Update your app env (SUPABASE_URL / SUPABASE_ANON_KEY) with the new project.
--
-- Notes:
--   - RLS is intentionally DISABLED (dev-friendly). Enable + add policies later.
--   - Script is idempotent: safe to re-run (uses IF NOT EXISTS / drops enums guarded).
--   - All PKs are bigint identity to match the original schema.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. Enums (USER-DEFINED types)
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'gender') then
    create type gender as enum ('male', 'female');
  end if;

  if not exists (select 1 from pg_type where typname = 'measure_weight') then
    create type measure_weight as enum ('daily', 'weekly', 'monthly');
  end if;
end$$;

-- -----------------------------------------------------------------------------
-- 1. role
-- -----------------------------------------------------------------------------
create table if not exists public.role (
  id   bigint generated by default as identity primary key,
  name varchar not null
);

-- -----------------------------------------------------------------------------
-- 2. account  (linked to Supabase auth.users)
-- -----------------------------------------------------------------------------
create table if not exists public.account (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users (id) on delete cascade,
  email        varchar,
  firstname    varchar,
  lastname     varchar,
  birthday     date,
  gender       gender,
  phone_number varchar,
  role_id      bigint references public.role (id) on delete set null,
  is_active    boolean not null default false,
  created_at   timestamptz not null default now()
);
create index if not exists idx_account_user_id on public.account (user_id);
create index if not exists idx_account_role_id on public.account (role_id);

-- -----------------------------------------------------------------------------
-- 3. health  (1-to-1 in practice with account)
-- -----------------------------------------------------------------------------
create table if not exists public.health (
  id              bigint generated by default as identity primary key,
  account_id      bigint references public.account (id) on delete cascade,
  height          integer,
  weight          real,
  target_weight   real,
  measure_weight  measure_weight,
  target_training smallint
);
create index if not exists idx_health_account_id on public.health (account_id);

-- -----------------------------------------------------------------------------
-- 4. training_objectives  (1-to-1 in practice with account)
-- -----------------------------------------------------------------------------
create table if not exists public.training_objectives (
  id                bigint generated by default as identity primary key,
  account_id        bigint references public.account (id) on delete cascade,
  training_per_week smallint,
  created_at        timestamptz not null default now()
);
create index if not exists idx_training_objectives_account_id on public.training_objectives (account_id);

-- -----------------------------------------------------------------------------
-- 5. account_health  (time-series weight measurements)
-- -----------------------------------------------------------------------------
create table if not exists public.account_health (
  id         bigint generated by default as identity primary key,
  account_id bigint references public.account (id) on delete cascade,
  weight     real,
  date       timestamptz not null default now()
);
create index if not exists idx_account_health_account_id on public.account_health (account_id);

-- -----------------------------------------------------------------------------
-- 6. group  ("group" is a reserved keyword -> must be quoted)
-- -----------------------------------------------------------------------------
create table if not exists public."group" (
  id          bigint generated by default as identity primary key,
  name        varchar,
  description text,
  create_by   bigint references public.account (id) on delete set null,
  created_at  timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- 7. account_group  (M2M account <-> group)
-- -----------------------------------------------------------------------------
create table if not exists public.account_group (
  id         bigint generated by default as identity primary key,
  account_id bigint references public.account (id) on delete cascade,
  group_id   bigint references public."group" (id) on delete cascade
);
create index if not exists idx_account_group_account_id on public.account_group (account_id);
create index if not exists idx_account_group_group_id on public.account_group (group_id);

-- -----------------------------------------------------------------------------
-- 8. workout_exercise_type  (exercise/workout categories)
-- -----------------------------------------------------------------------------
create table if not exists public.workout_exercise_type (
  id   bigint generated by default as identity primary key,
  name varchar not null
);

-- -----------------------------------------------------------------------------
-- 9. exercise  (catalog: wger import or custom)
-- -----------------------------------------------------------------------------
create table if not exists public.exercise (
  id                 bigint generated by default as identity primary key,
  title              varchar not null,
  subtitle           varchar,
  muscle_group       varchar,
  secondary_muscles  varchar,
  equipment          varchar,
  image_url          text,
  instructions       text,
  body_weight        boolean not null default false,
  is_custom          boolean not null default true,
  account_id         bigint references public.account (id) on delete cascade,
  type_id            bigint references public.workout_exercise_type (id) on delete set null,
  created_at         timestamptz not null default now()
);
create index if not exists idx_exercise_account_id on public.exercise (account_id);
create index if not exists idx_exercise_type_id on public.exercise (type_id);

-- -----------------------------------------------------------------------------
-- 10. workout  (workout templates)
-- -----------------------------------------------------------------------------
create table if not exists public.workout (
  id         bigint generated by default as identity primary key,
  account_id bigint references public.account (id) on delete cascade,
  type_id    bigint references public.workout_exercise_type (id) on delete set null,
  title      varchar,
  subtitle   varchar,
  created_at timestamptz not null default now()
);
create index if not exists idx_workout_account_id on public.workout (account_id);
create index if not exists idx_workout_type_id on public.workout (type_id);

-- -----------------------------------------------------------------------------
-- 11. workout_block  (supersets / trisets / giant sets / dropsets)
-- -----------------------------------------------------------------------------
create table if not exists public.workout_block (
  id         bigint generated by default as identity primary key,
  workout_id bigint not null references public.workout (id) on delete cascade,
  type       varchar not null default 'superset'
             check (type in ('superset', 'triset', 'giant_set', 'dropset')),
  title      varchar,
  "order"    smallint,
  created_at timestamptz not null default now()
);
create index if not exists idx_workout_block_workout_id on public.workout_block (workout_id);

-- -----------------------------------------------------------------------------
-- 12. workout_exercise  (exercise config inside a workout)
-- -----------------------------------------------------------------------------
create table if not exists public.workout_exercise (
  id          bigint generated by default as identity primary key,
  workout_id  bigint not null references public.workout (id) on delete cascade,
  exercise_id bigint not null references public.exercise (id) on delete cascade,
  block_id    bigint references public.workout_block (id) on delete set null,
  "set"       smallint default 3,
  repetitions integer  default 10,
  weight      real     default 0,
  rest        smallint default 60,
  "order"     smallint,
  created_at  timestamptz not null default now()
);
create index if not exists idx_workout_exercise_workout_id on public.workout_exercise (workout_id);
create index if not exists idx_workout_exercise_exercise_id on public.workout_exercise (exercise_id);
create index if not exists idx_workout_exercise_block_id on public.workout_exercise (block_id);

-- -----------------------------------------------------------------------------
-- 13. workout_group  (M2M workout <-> group)
-- -----------------------------------------------------------------------------
create table if not exists public.workout_group (
  id         bigint generated by default as identity primary key,
  workout_id bigint references public.workout (id) on delete cascade,
  group_id   bigint references public."group" (id) on delete cascade,
  created_at timestamptz not null default now()
);
create index if not exists idx_workout_group_workout_id on public.workout_group (workout_id);
create index if not exists idx_workout_group_group_id on public.workout_group (group_id);

-- -----------------------------------------------------------------------------
-- 14. program  (training programs)
-- -----------------------------------------------------------------------------
create table if not exists public.program (
  id             bigint generated by default as identity primary key,
  account_id     bigint not null references public.account (id) on delete cascade,
  title          varchar not null,
  description    text,
  duration_weeks smallint not null default 4,
  start_date     date not null,
  end_date       date not null,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now()
);
create index if not exists idx_program_account_id on public.program (account_id);

-- -----------------------------------------------------------------------------
-- 15. program_workout  (workouts scheduled within a program)
-- -----------------------------------------------------------------------------
create table if not exists public.program_workout (
  id          bigint generated by default as identity primary key,
  program_id  bigint not null references public.program (id) on delete cascade,
  workout_id  bigint not null references public.workout (id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 1 and 7),
  week_number smallint not null check (week_number >= 1),
  created_at  timestamptz not null default now()
);
create index if not exists idx_program_workout_program_id on public.program_workout (program_id);
create index if not exists idx_program_workout_workout_id on public.program_workout (workout_id);

-- -----------------------------------------------------------------------------
-- 16. workout_session  (a performed workout)
-- -----------------------------------------------------------------------------
create table if not exists public.workout_session (
  id          bigint generated by default as identity primary key,
  account_id  bigint references public.account (id) on delete cascade,
  workout_id  bigint references public.workout (id) on delete set null,
  notes       text,
  created_at  timestamptz not null default now(),  -- session start
  finished_at timestamptz                          -- null = in progress
);
create index if not exists idx_workout_session_account_id on public.workout_session (account_id);
create index if not exists idx_workout_session_workout_id on public.workout_session (workout_id);

-- -----------------------------------------------------------------------------
-- 17. workout_session_exercise
-- -----------------------------------------------------------------------------
create table if not exists public.workout_session_exercise (
  id                  bigint generated by default as identity primary key,
  workout_session_id  bigint not null references public.workout_session (id) on delete cascade,
  workout_exercise_id bigint not null references public.workout_exercise (id) on delete cascade,
  "order"             smallint,
  notes               text,
  created_at          timestamptz not null default now()
);
create index if not exists idx_wse_session_id on public.workout_session_exercise (workout_session_id);
create index if not exists idx_wse_workout_exercise_id on public.workout_session_exercise (workout_exercise_id);

-- -----------------------------------------------------------------------------
-- 18. workout_session_set  (actual performance data)
-- -----------------------------------------------------------------------------
create table if not exists public.workout_session_set (
  id                          bigint generated by default as identity primary key,
  workout_session_exercise_id bigint not null references public.workout_session_exercise (id) on delete cascade,
  set_number                  smallint not null,
  repetitions                 integer,
  weight                      real,
  body_weight                 boolean default false,
  completed                   boolean not null default false,
  created_at                  timestamptz not null default now()
);
create index if not exists idx_wss_session_exercise_id on public.workout_session_set (workout_session_exercise_id);

-- =============================================================================
-- SEED DATA
-- =============================================================================

-- Roles
insert into public.role (name)
select v.name
from (values ('ROLE_ADMIN'), ('ROLE_USER')) as v(name)
where not exists (select 1 from public.role r where r.name = v.name);

-- Exercise / workout types
insert into public.workout_exercise_type (name)
select v.name
from (values
  ('Strength'),
  ('Cardio'),
  ('Mobility'),
  ('Hypertrophy'),
  ('Endurance')
) as v(name)
where not exists (
  select 1 from public.workout_exercise_type t where t.name = v.name
);

-- =============================================================================
-- End of schema
-- =============================================================================
